# Generated by Django 5.0.2 on 2024-02-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='printingVersion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=180),
        ),
    ]
