# Generated by Django 5.0.2 on 2024-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_book_author_book_printingversion_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='printingVersion',
            field=models.CharField(max_length=150),
        ),
    ]
