# Generated by Django 5.0.2 on 2024-02-23 20:37

import django.db.models.deletion
import project.utils.app_constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_guest_borrow_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default=project.utils.app_constant.BOOK_STATUES['AVAILABLE'], max_length=30),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to='library_app.book'),
        ),
    ]
